### ISSUE TITLE
Wamsley2012 peak_val_det is incorrect

### ISSUE THREAD

**Issue by bdyetton** [wonambi-python/wonambi#18]
Hi Wonambi Team,
Looks like there is a bug in the Wamsley2012 algo (and maybe others)
The spindle amplitudes in peak_val_det are off by a good factor of 1e7 (values around 500,000,000).
For example, running the Ferrarelli2007 algorithm on the same data gives values around 50uV

**Comment by jnobyrne** [comment]
Hi Benjamin,

Thanks for your comments!

I had not realized what outlandish numbers the Wamsley2012 detector was giving for peak_val_det. The reason for this is that the signal used for thresholding in this method is the square of the real part of the square of the continuous wavelet transform of the raw signal. This pretty much results in raising the filtered signal to the power of 4. This _detection signal_ was then being used to return _det_ values such as peak_val_det. I realize these enormous numbers are unwieldly and difficult to interpret. I've changed the method so that _det_ values are taken from the absolute value of the continuous wavelet transform, before any squaring, yielding values in a more familiar range. The changes are in version 5.71.

Happy hunting,
Jordan

**Comment by bdyetton** [comment]
Awesome, cheers mate!
