### ISSUE TITLE
Spindle/SO detectors for non-artifacted

### ISSUE THREAD

**Issue by bdyetton** [wonambi-python/wonambi#19]
Hi Wonambi,
There are a few detectors that require artifact free NREM sleep. Does this mean the other methods should be able to work with NREM with artifacts? 

Also, when they require NREM sleep, does this mean I should slice out the REM/Wake and concatenate NREM segments together? Or can I just ignore the spindles detected in REM/Wake segments after the fact?
I would say the former is safer, especially if a method is thresholding spindles based on some global property of the signal (e.g. X must be > 3*Std Dev of signal).

**Comment by jnobyrne** [comment]
Hi bdyetton,

The [Wonambi documentation](https://wonambi-python.github.io/gui/methods.html#spindle-detection-methods) recommends the use of artefact-free signal whenever this was explicitly specified in the original paper. In cases where it is not specified, it may be that the authors assumed artefact exclusion as a basic pre-processing step. In any case, my recommendation would be to exclude artefacts wherever possible.

As to your second question, you are correct that the former method is best, i.e. to run detection on concatenated NREM epochs only. Indeed, the thresholding would otherwise be thrown off by the intervening Wake and REM signal.

Note that some of these methods use NREM for thresholding and then run the detection on all signal. Wonambi doesn't currently offer this option, as we do not see much of a need to detect spindles outside of NREM sleep.

Thanks for your questions!
Jordan

**Comment by bdyetton** [comment]
Awesome, thanks Jordan! I was wondering why I was getting different answers to our Matlab version of Wamsley2012, and this is probably it.
